<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="LT2025" failures="4" tests="10" name="Surefire test" time="21.583" errors="0" timestamp="2025-08-10T12:15:50 IST">
  <testcase classname="tests.AddToCartTest" name="AppLogin" time="10.783"/>
  <testcase classname="tests.AddToCartTest" name="AddSingleItem_ToCart" time="0.73"/>
  <testcase classname="tests.AddToCartTest" name="MultipleItems_ToCart" time="8.338">
    <failure type="java.lang.AssertionError" message="Expected to Add 1 item to cart expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: Expected to Add 1 item to cart expected [3] but found [2]
at tests.AddToCartTest.MultipleItems_ToCart(AddToCartTest.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- MultipleItems_ToCart -->
  <testcase classname="tests.AddToCartTest" name="RemovefromCart" time="0.0">
    <skipped/>
  </testcase> <!-- RemovefromCart -->
  <testcase classname="tests.CheckoutTest" name="checkout_withoutItems" time="0.003">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;pages.CheckoutPage.noOrderCheckout()&amp;quot; because &amp;quot;this.ckp&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pages.CheckoutPage.noOrderCheckout()" because "this.ckp" is null
at tests.CheckoutTest.checkout_withoutItems(CheckoutTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- checkout_withoutItems -->
  <testcase classname="tests.CheckoutTest" name="CheckoutOrder" time="0.003">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;pages.CheckoutPage.checkout_Order()&amp;quot; because &amp;quot;this.ckp&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pages.CheckoutPage.checkout_Order()" because "this.ckp" is null
at tests.CheckoutTest.CheckoutOrder(CheckoutTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- CheckoutOrder -->
  <testcase classname="tests.CheckoutTest" name="place_order" time="0.0">
    <skipped/>
  </testcase> <!-- place_order -->
  <testcase classname="tests.LoginTest" name="loginApp" time="0.001">
    <failure type="java.lang.AssertionError" message="Login Failed expected [https://bstackdemo.com/?signin=true] but found [null]">
      <![CDATA[java.lang.AssertionError: Login Failed expected [https://bstackdemo.com/?signin=true] but found [null]
at tests.LoginTest.loginApp(LoginTest.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- loginApp -->
  <testcase classname="tests.LoginTest" name="loginApp_with_EmptyCredentials" time="0.001"/>
  <testcase classname="tests.LoginTest" name="loginApp_with_invalid_Credentials" time="0.001"/>
  <testcase classname="tests.BaseTest" name="@AfterTest closeApp" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest closeApp -->
  <testcase classname="tests.BaseTest" name="@AfterTest closeApp" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest closeApp -->
  <testcase classname="tests.BaseTest" name="@AfterTest closeApp" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest closeApp -->
  <testcase classname="tests.BaseTest" name="@BeforeTest initialSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest initialSetup -->
  <testcase classname="tests.BaseTest" name="@BeforeTest initialSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest initialSetup -->
  <testcase classname="tests.BaseTest" name="@BeforeTest initialSetup" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest initialSetup -->
</testsuite> <!-- Surefire test -->
